### ISSUE TITLE
Have `--get-id` flag of `search` produce `.csv` or `.txt` file

### ISSUE THREAD

**Issue by Quiet27** [QUT-Digital-Observatory/youte#13]
Currently, when using the `--get-id` flag of the `search` function to retrieve IDs only, a `.json` or `.jsonl` file will be returned. It would be a great to have the IDs exported/saved as `.txt` or `.csv` so that this file could then be used later with the `hydrate` function.

**Comment by boyd-nguyen** [comment]
Added a `dehydrate` command to extract IDs from JSON file: 3dcbfd015ab503dbdafc0cea8d8e5705956ddd20
