### ISSUE TITLE
Handle video IDs that start with dashes (related-to option)

### ISSUE THREAD

**Issue by katkasian** [QUT-Digital-Observatory/youte#35]
First, thank you for all your incredible work on youte - it's been really useful. 

I wanted to flag a minor issue with video IDs that start from dashes (for example, `-Q7G5zfSal8`). I would like to collect videos related to this video, but youte interprets it as an argument. I tried adding another dash or using quotation marks but could not get it to be treated as a value for the first positional argument. Instead, I always get an error `Error: No such option: -Q`. 

Any help or advice would be much appreciated!

**Comment by boyd-nguyen** [comment]
@katkasian Thanks for pointing this out! With IDs such as those, one way would be to escape the dash. How to escape the dash differs depending on your shell. In Bash, adding a `--` before will do the trick - everything after it will be interpreted as raw strings. So in your case, I would do `youte related-to -o related_videos.json -- -Q7G5zfSal8`. Note the space between the `--` and the video ID.

Alternatively, if you have multiple IDs starting with a dash, a better way to do it would be to put the IDs in a text file, one ID per line, and refer to that file in your command with the `-f` option. For example, `youte related-to -f ids.txt -o related_videos.json`. You can learn more about this `-f` option [here](https://youte.readthedocs.io/en/latest/documentation/#use-ids-from-text-file).
