### ISSUE TITLE
Suggestion for docs: Explanation for NA values in channels.like_count and videos.like_count

### ISSUE THREAD

**Issue by Quiet27** [QUT-Digital-Observatory/youte#4]
I noticed that the like_count for some channels and videos was NA, and it turns out this is correct (channels have like count hidden, and videos don't seem to have like count showing on YouTube), but it might confuse people. I have a minor suggestion to put a note about this in the documentation just so people understand what's happening 😸

**Comment by boyd-nguyen** [comment]
resolved with b89418e075fe2e755d2cd65c5954be0220a8965a
