### ISSUE TITLE
pydantic, orm_mode error ? API ? 

### ISSUE THREAD

**Issue by bonnebulle** [QUT-Digital-Observatory/youte#40]
I have an error issue...
So I try refresh a new API (v3)
```
.../pipx/venvs/youte/lib/python3.11/site-packages/pydantic/_internal/_config.py:317: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
INFO | Getting API key from config file.
INFO | Getting page 1
^C
Aborted!
```

Do i need to upgrade ```pydantic``` ?

My youte version...
```bash
youte --version 
youte, version 2.4.1
```

Thanks

**Comment by boyd-nguyen** [comment]
@bonnebulle that looks like a warning from Pydantic. Pydantic was recently updated to v2, while youte still uses v1. The changes in v2 should not affect youte, however. Did you run into any other error message?

**Comment by bonnebulle** [comment]
Sad news.
Hum I downgrade 
```
Name: pydantic
Version: 1.10.13
```
same issue, no other error message..
How can I help, search ?

**Comment by boyd-nguyen** [comment]
@bonnebulle Could you show me the steps you did and the error message you got?

**Comment by bonnebulle** [comment]
Hey, thanks for quick answer !
I just upgrade all my python packages...
( including ```wfuzz``` )
but downgrade ```pydantic``` 
(like I said previously)
(I will try a  ```pydantic``` upgrade to determine if it changing anyting)

So, now,
I keep have the same error...
but ```youte``` do the job.
You can find my bash script [here](https://gist.github.com/bonnebulle/1fbcd16f41bdc1cb26986be19bc87f3e)

**Comment by boyd-nguyen** [comment]
@bonnebulle Did the script stop running and nothing was returned, or did it just show you the UserWarning messages? Could you show me the output when you run the bash script? I can't run the script for some reason.
