### ISSUE TITLE
Hang on using tidy for json

### ISSUE THREAD

**Issue by Lingomat** [QUT-Digital-Observatory/youte#43]
I thought it was a bit puzzling I have to specify --tidy-to and -o. They seem exclusive. Or at least if writing to the raw json is required, then one might as well make a tidy command which converts the json to the desired format.

At any rate, the following command just locked up Youte for 20 minutes at 100% CPU (until I Ctrl-C'd it) after downloading comments for 50 odd videos. It finished the download, it seems, filled comments_untidied.json and created comments_tidied.json but wrote nothing in it.

`youte comments --by-video-id --file-path video_ids.txt --format json -o comments_untidied.json --tidy-to comments_tidied.json`

**Comment by boyd-nguyen** [comment]
@Lingomat `-o` stores the raw json and is required, whereas `--tidy-to` parses the json to a CSV and is optional
